### ISSUE TITLE
Add FROGS in galaxy toolshed

### ISSUE THREAD

**Issue by fescudie** [geraldinepascal/FROGS#1]
Propose FROGS in the galaxy toolshed.

**Comment by vebaev** [comment]
Dear all,
is FROGS present in toolshed? How can I install it on my local Galaxy instance?

Vesko

**Comment by mariabernard** [comment]
Hi,

No, that was an idea, but this is not a priority for us.

it's normally very easy to add FROGS on a local instance. Just follow the step indicated in the readme file.

If any trouble I could help.

Best Regards

Maria

**Comment by vebaev** [comment]
Thanks for the reply, I do not feel comfortable doing this manually as I can break something on my Galaxy. Maybe I will wait when there is an automated package or something?

**Comment by mariabernard** [comment]
I understand your concern, but developing a "FROGS toolshed" is a lot of work for us and for now its not planned, I'm sorry.

**Comment by Slugger70** [comment]
Hi FROGS devs, I'm at the Galaxy hackathon at the moment and am going to attempt to put FROGS into conda and the galaxy toolshed.

**Comment by geraldinepascal** [comment]
Dear Slugger70, it is an excellent initiative. It will help us a lot, because we are currently lacking developing forces and therefore we have not postponed the setting in the FROGS toolsheld. However, at the end of this week, a big release is planned with the addition of 8 tools and the integration of the corrected XML files for the tools already online. Indeed, there are currently a lot of language mistakes in XML. Will it be difficult for you to later integrate the new XML in the toolshed?

**Comment by Slugger70** [comment]
That's fine. It's pretty easy to get a new version one the old one is working and I might not get it all done over the next couple of days anyway.

**Comment by geraldinepascal** [comment]
Dear Slugger70, I have a question for you. Do you use FROGS on a academic galaxy platform ? or on a galaxy in your PC ?

**Comment by Slugger70** [comment]
We use it at the moment on a couple of galaxy servers for different departments of our university. We would like to expand it's use however to other servers.. Having gone through the manual install process twice, I'm keen to not have to do it again and therefore want to automate it.

**Comment by geraldinepascal** [comment]
could you write me on frogs@inra.fr the name of the different departments of our university. Its for our quality approach.

**Comment by mariabernard** [comment]
done
