### ISSUE TITLE
Preprocess tool: Improving the management of samples names

### ISSUE THREAD

**Issue by geraldinepascal** [geraldinepascal/FROGS#13]
Check when you untar the names of samples is valid.
An archive containing files toto.1, toto.2, toto.3 is not valid, the dot is not for the moment accepted.

**Comment by fescudie** [comment]
When the user provides already contiged data without provide samples names, these names are extracted from filenames. It is difficult to validate these names.
I have added an exception when several files produce the same sample name: "Impossible to retrieve unique samples names from files. The sample name must be before the first dot."

**Comment by fescudie** [comment]
The commit has been merged in the master branch.
