### ISSUE TITLE
Preprocessing tool: sample name format

### ISSUE THREAD

**Issue by mariabernard** [geraldinepascal/FROGS#14]
If sample name has 'space' in it, preprocess crashes. 
Maybe the prevent_shel_injections function doesn't work very well.

**Comment by fescudie** [comment]
To prevent downstream problems I have added an exception on the parameter: "A sample name must not contain white spaces."
This is not the role of prevent_shel_injections.

**Comment by fescudie** [comment]
The commit has been merged in the master branch.
