### ISSUE TITLE
Upload_tar has a bug with recent galaxy releases

### ISSUE THREAD

**Issue by fescudie** [geraldinepascal/FROGS#18]
The current version of upload_tar does not work with the current galaxy.
This is due to changes in galaxy API.

**Comment by fescudie** [comment]
The standard upload can be used if the user uncheck the option 'Use POSIX standard' in settings.

**Comment by mariabernard** [comment]
Or add a tar datatype in galaxy : https://github.com/galaxyproject/galaxy/pull/2636/commits/a8147e537cf8e894d6d5032220909d211235d72f

(pull request accepted in future version of Galaxy : https://github.com/galaxyproject/galaxy/pull/2636 )
