### ISSUE TITLE
Primers at Pre Process

### ISSUE THREAD

**Issue by ciellie** [geraldinepascal/FROGS#19]
Please make the Primer fields mandatory otherwise the pre-process crashes

**Comment by mariabernard** [comment]
I thought it was already done.
Correction is on branch dev (https://github.com/geraldinepascal/FROGS/commit/6605682df2b516dc0cd5d2634af78f7241ced3b4), we will merge it with master soon.

Thank you for the issue

**Comment by mariabernard** [comment]
correction merge on the master branch.
