### ISSUE TITLE
FROGS Affiliation OTU version (0.8.0) : No options available for "Using reference database"

### ISSUE THREAD

**Issue by inestiouiri** [geraldinepascal/FROGS#20]
![frogs_affiliation_otu](https://cloud.githubusercontent.com/assets/15051266/19721934/52f97332-9b6c-11e6-8618-f741df00d887.png)

**Comment by mariabernard** [comment]
Do you have any trouble ? I think that you did not fill a frogs_db.loc in you tool_data folder.
- Upload databanks and indexes from http://genoweb.toulouse.inra.fr/frogs_databanks/assignation
  - Extract databanks.
  - To use these databank, you need to create a .loc file named
    'frogs_db.loc'. The path provided must be the '.fasta'.

same thing in the filter tool, there is a section to filter contaminant which call phiX_db.loc (for now we provide only phiX contaminant)
    - Upload databank and indexes from http://genoweb.toulouse.inra.fr/frogs_databanks/contaminants
    - Extract databank.
    - To use this databank, you need to create a .loc file named
      'phiX_db.loc'. The path provided must be the '.fasta'.

format must be "name"TAB"pah_to_fasta_file

Hope this help.

**Comment by pbordron** [comment]
Can you provide an example in the README. There is no information provided about the expected format in *.loc files.

**Comment by mariabernard** [comment]
Hi, 

you are perfectly right. I will add frogs_db.loc and phix_db.loc examples.
The answer for both file is a tabulated file with 2 columns:

-  first is the name you want to see in galaxy  (must be uniq)
- second is the database fasta file (indexed files must be in the same directories)

Regards

Maria

PS: please open an new issue next time
