### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by nagoue** [geraldinepascal/FROGS#25]
Hi,
I am testing FROGS on local computer (Ubuntu) and I am facing a basic problem. I cloned the git repository and installed dependencies. At the test step, I got this error:

`IOError: [Errno 2] No such file or directory: '/home/Logiciels/galaxy17_05/galaxy/tools/my_tools/FROGS/libexec/preprocess_tpl.html'
Error in preprocess`
Why does it look for the preprocess_tpl.html file in the libexec folder? This file is localized in tools/preprocess folder and the symlink is in the app folder.
Should I create a symlink to libexec folder ? This option sounds strange to me...
Thank you,
Nadia

**Comment by mariabernard** [comment]
Hello Nadia,

We agree that you clone the master branch of the git repository ?

Correct me if I am wrong, but it seems that you make some links of the python script of each tool in the libexec directory, no ?
Normally you do not need to do anything like this.

Just : 
- clone the master repository
- in the **libexec** folder, add links for software used in FROGS : flash, cutadapt, swarm, vsearch, blastn, jar of RDP classifier, RScript ...... (everything in the dependancies section of the README)
- in the tool_conf.xml Galaxy file just add tools by writing path of the FROGS XML files available in the **app** folder (or simply copy and paste line from the readme)
- in the static/images Galaxy folder, make a link named frogs to the FROGS/img folder.

and this is it.

Does this help ?

**Comment by nagoue** [comment]
Hi Maria,

I cloned the master branch like this 
`git clone https://github.com/geraldinepascal/FROGS.git`
I haven't made symlink  but just suggesting that could maybe solve my error problem.
Dependencies were in my PATH so I changed and made links in the libexec to the required tools.

The error message changed to 
test.sh: ligne 28: preprocess.py : command not found
Error in preprocess

In FROGS/app : 
preprocess.py -> ../tools/preprocess/preprocess.py*
preprocess_tpl.html -> ../tools/preprocess/preprocess_tpl.html
preprocess.xml -> ../tools/preprocess/preprocess.xml

In FROGS/tools/preprocess 
preprocess.py*
preprocess_tpl.html
preprocess.xml

Sorry, I am not familiar with python. The one installed is python 2.7.13
It looks like an environment issue.

Thank you

**Comment by mariabernard** [comment]
could you list your libexec directory ?
what is the test.sh command line you used ?

**Comment by nagoue** [comment]
my libexec directory:
drwxrwxr-x  2 nagoue nagoue  4096 oct.  10 13:21 ./
drwxrwxr-x 10 nagoue nagoue  4096 oct.   6 11:43 ../
-rwxrwxr-x  1 nagoue nagoue 12133 sept. 27 14:58 addAffiliation2biom.py*
-rwxrwxr-x  1 nagoue nagoue 10702 sept. 27 14:58 biom2tsv.py*
-rwxrwxr-x  1 nagoue nagoue  3594 sept. 27 14:58 biomFastaUpdate.py*
-rwxrwxr-x  1 nagoue nagoue 26717 sept. 27 14:58 biomTools.py*
lrwxrwxrwx  1 nagoue nagoue    15 oct.  10 11:18 blastn -> /usr/bin/blastn*
lrwxrwxrwx  1 nagoue nagoue    71 oct.  10 11:22 classifier.jar -> /home/nagoue/Logiciels/miniconda2/share/rdptools-2.0.2-0/classifier.jar
lrwxrwxrwx  1 nagoue nagoue    32 oct.  10 11:17 cutadapt -> /home/nagoue/.local/bin/cutadapt*
-rwxrwxr-x  1 nagoue nagoue 16792 sept. 27 14:58 derepSamples.py*
-rwxrwxr-x  1 nagoue nagoue  3942 sept. 27 14:58 extractSwarmsFasta.py*
-rwxrwxr-x  1 nagoue nagoue  9910 sept. 27 14:58 filterSeq.py*
lrwxrwxrwx  1 nagoue nagoue    20 oct.  10 11:16 flash -> /usr/local/bin/flash*
-rwxrwxr-x  1 nagoue nagoue  4393 sept. 27 14:58 multiAffiFromBiom.py*
-rwxrwxr-x  1 nagoue nagoue 28734 sept. 27 14:58 parallelChimera.py*
-rwxrwxr-x  1 nagoue nagoue 11012 sept. 27 14:58 remove454Adapt.py*
-rwxrwxr-x  1 nagoue nagoue 12833 sept. 27 14:58 removeConta.py*
-rwxrwxr-x  1 nagoue nagoue  1401 sept. 27 14:58 root_tree.R*
-rwxrwxr-x  1 nagoue nagoue 18685 sept. 27 14:58 silva2retrainRDP.py*
-rwxrwxr-x  1 nagoue nagoue  6525 sept. 27 14:58 sortAbundancies.py*
-rwxrwxr-x  1 nagoue nagoue 26705 sept. 27 14:58 splitbc.pl*
lrwxrwxrwx  1 nagoue nagoue    14 oct.  10 11:17 swarm -> /usr/bin/swarm*
-rwxrwxr-x  1 nagoue nagoue  5329 sept. 27 14:58 swarm2biom.py*
-rwxrwxr-x  1 nagoue nagoue 14040 sept. 27 14:58 tsv2biom.py*
lrwxrwxrwx  1 nagoue nagoue    16 oct.  10 11:18 vsearch -> /usr/bin/vsearch*

The command I launched is from FROGS/test directory:

$ bash test.sh /home/nagoue/Logiciels/galaxy17_05/galaxy_tools/FROGS/test/ 2 4 /home/nagoue/Documents/results/galaxy/

**Comment by mariabernard** [comment]
The libexec is ok

But your command line is wrong! 
Assuming that you clone FROGS in /home/nagoue/Logiciels/galaxy17_05/galaxy_tools/, remove "test/" at the end of your FROGS_PATH
<pre>
bash test.sh /home/nagoue/Logiciels/galaxy17_05/galaxy_tools/FROGS/ 2 4 /home/nagoue/Documents/results/galaxy/ </pre>

**Comment by nagoue** [comment]
That's right! but I still have the error message:

Step preprocess mardi 10 octobre 2017, 14:46:10 (UTC+0200)
test.sh: ligne 28: preprocess.py : command not found
Error in preprocess

**Comment by mariabernard** [comment]
It should work. We miss something!

Could you:
<pre>
ls /home/nagoue/Logiciels/galaxy17_05/galaxy_tools/FROGS
</pre>
and 
<pre>
ls /home/nagoue/Logiciels/galaxy17_05/galaxy_tools/FROGS/app
</pre>

in my case, in a new session
<pre> 
preprocess.py
preprocess.py : commande introuvable
</pre>
if I execute the first line of the test.sh
<pre>
frogs_dir=/home/maria/workspace/git/FROGS_master
export PATH=$frogs_dir/libexec:$frogs_dir/app:$PATH
export PYTHONPATH=$frogs_dir/lib:$PYTHONPATH
preprocess.py
usage: preprocess.py [-h] [-v] {illumina,454} ...
preprocess.py: error: too few arguments
</pre>

it works.

**Comment by nagoue** [comment]
OK, I found a mistake in my path. Shame on me!!
I apologize for your time.
Thank you Maria !
