### ISSUE TITLE
FROGS Tree Reconstruction of phylogenetic tree issue

### ISSUE THREAD

**Issue by mariemh23** [geraldinepascal/FROGS#30]
Hello, 

I try to run Frogs tree. I put the fasta file and the biom abundance file (from filter step 4 of FROGS tutorial : http://sepsis-omics.github.io/tutorials/modules/frogs/#output_3 ). However, I got this erreur :

File "/usr/local/galaxy/tools/FROGS_2/app/tree.py", line 147, in get_version
    return Cmd.get_version(self, 'stdout').split()[-1].strip()
**IndexError: list index out of range**

any help? thx

**Comment by mariabernard** [comment]
Hello,

could you share these files ?  and Could you indicate me the command line you use ?

Regards

**Comment by mariemh23** [comment]
Dear @mariabernard 
This is my command line :
python2.7 /usr/local/galaxy/tools/FROGS_2/app/tree.py --input-otu /scratch/database/files/023/dataset_23055.dat --biomfile /scratch/database/files/023/dataset_23056.dat --nb-cpus 1 --out-tree /scratch/database/files/023/dataset_23345.dat --html /scratch/database/files/023/dataset_23346.dat

and please find attached input files 

[Filter_data.gz](https://github.com/geraldinepascal/FROGS/files/1937637/Filter_data.gz)

thx

**Comment by mariabernard** [comment]
Filter_data.gz is corrupted. I see the begining of the abundance biom file, but its not completed, and I need the fasta file also

**Comment by mariemh23** [comment]
Sorry... and now?
[Filter_galaxy.gz](https://github.com/geraldinepascal/FROGS/files/1937770/Filter_galaxy.gz)

**Comment by mariabernard** [comment]
I successfully construct the tree
python ~/workspace/git/FROGS/FROGS_master/app/tree.py -i Filters__sequences.fasta -b FROGS_Filters__abundance.biom1

Here are the results:  http://genoweb.toulouse.inra.fr/~mbernard/mariemh23_github/

are you sure about your input in Galaxy ?

**Comment by mariemh23** [comment]
Thanks for your help .

I  tried the same line command as you on our server : /usr/local/galaxy/tools/FROGS_2/app/tree.py --input-otu Filter_galaxy2/Filters__sequences.fasta --biomfile Filter_galaxy2/FROGS_Filters__abundance.biom1

. I always get the same mistake. 
Application
Software :/usr/local/galaxy/tools/FROGS_2/app/tree.py (version : 1.0.0)
Command : /usr/local/galaxy/tools/FROGS_2/app/tree.py --input-otu Filter_galaxy2/Filters__sequences.fasta --biomfile Filter_galaxy2/FROGS_Filters__abundance.biom1

Number of input OTUs sequences: 1702

# Mafft multiple alignment. (mafft version : v7.205)
Command:
	mafft --auto --thread 1 Filter_galaxy2/Filters__sequences.fasta > Filters__sequences_mafft_aligned.fasta 2> /dev/null

Execution:
	start: 23 Apr 2018 12:11:27
	end:   23 Apr 2018 12:11:36

# reconstruction a phylogenetic tree (FastTree version : 2.1.10)
Command:
	FastTree -nt -gtr Filters__sequences_mafft_aligned.fasta > 1524481887.66_88772_Filters__sequences.fasttree 2> /dev/null

Execution:
	start: 23 Apr 2018 12:11:36
	end:   23 Apr 2018 12:12:10

Traceback (most recent call last):
  File "/usr/local/galaxy/tools/FROGS_2/app/tree.py", line 330, in <module>
    RootTree(fasttree, args.out_tree).submit(args.log_file)
  File "/usr/local/galaxy/tools/FROGS_2/lib/frogsUtils.py", line 135, in submit
    FH_log.write( '# ' + self.description + ' (' + os.path.basename(self.program) + ' version : ' + self.get_version() + ')\n' )
  File "/usr/local/galaxy/tools/FROGS_2/app/tree.py", line 147, in get_version
    return Cmd.get_version(self, 'stdout').split()[-1].strip()
IndexError: list index out of range

 Where do you think the problem resides?

**Comment by mariabernard** [comment]
If you compare with my log.txt file:
* mafft and fasttree run ok
* root_tree.R not

could you test this:

```
export PATH=/usr/local/galaxy/tools/FROGS_2/libexec:$PATH
root_tree.R -v
```

**Comment by mariemh23** [comment]
Dear Maria, 

it seems that the function is not installed in my serveur ? Is it an R package? If so, which one?
root_tree.R: command not found

**Comment by mariabernard** [comment]
Hello,

It's an R script that we developped. It should be there : <FROGS_path>/libexec/root_tree.R .
Do you have it ?
Does it have execution rigths?

**Comment by mariemh23** [comment]
Hi, 

we installed the script correctly and checked the execution rights. I tried again " root_tree.R  -v  " and I got this

* caught segfault *
address 0x6, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(package, lib.loc)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
 8: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
 9: library(ape)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault

**Comment by mariabernard** [comment]
What is you version of R ? We assure that the scripts work with the version 3.4.0
This script import two packages ape and phangorn (cf Readme).
(NB: ape is not precised in the readme as it is a dependancy of Phyloseq. )

Do you have these pakages installed ?
```
R
library(ape)
library(phangorn)
```
