### ISSUE TITLE
IMPROVEMENT - Assignation databank descriptions

### ISSUE THREAD

**Issue by Toliman06** [geraldinepascal/FROGS#32]
Is it possible to have a short description of the databank found here? Creating a readme.txt describing databanks in each folder plus in the GitHub readme could be really usefull.

Something like this (I did the annoying part...):

16S/
- greengenes_13_5.tar.gz --> data related to the greengenes 13.5 database (http://greengenes.secondgenome.com/)
- silva_123_16S.tar.gz -->  data related to the SILVA 123 16S database (https://www.arb-silva.de/download/arb-files/)
- silva_128_16S.tar.gz --> data related to the SILVA 128 16S database (https://www.arb-silva.de/download/arb-files/)
- silva_128_16S_pintail50.tar.gz --> ???
- silva_128_16S_pintail80.tar.gz --> ???
- silva_128_16S_pintail100.tar.gz --> ???
- silva_132_16S.tar.gz --> data related to the SILVA 132 16S database (https://www.arb-silva.de/download/arb-files/)
- silva_132_16S_pintail50.tar.gz --> ???
- silva_132_16S_pintail80.tar.gz --> ???
- silva_132_16S_pintail100.tar.gz --> ???

18S/
- pr2_gb203_4.5.tar.gz --> data related to the The Protist Ribosomal Reference (PR2) database v4.5 (https://github.com/vaulot/pr2_database/releases)
- silva_119-1_18S.tar.gz -->  data related to the SILVA 119-1 18S database (https://www.arb-silva.de/download/arb-files/)
- silva_123_18S.tar.gz -->  data related to the SILVA 123 18S database (https://www.arb-silva.de/download/arb-files/)
 - silva_128_18S.tar.gz -->  data related to the SILVA 128 18S database (https://www.arb-silva.de/download/arb-files/)
 - silva_132_18S.tar.gz -->  data related to the SILVA 132 18S database (https://www.arb-silva.de/download/arb-files/)

23S/
- silva_123_23S.tar.gz  -->  data related to the SILVA 123 23S database (https://www.arb-silva.de/download/arb-files/)
- silva_128_23S.tar.gz --> data related to the SILVA 128 23S database (https://www.arb-silva.de/download/arb-files/)
- silva_132_23S.tar.gz --> data related to the SILVA 132 23S database (https://www.arb-silva.de/download/arb-files/)

MiDas/ (??? mitochondrial associated? Microbes of Activated Sludge and Anaerobic Digesters ???)
- MiDAS_S119_1.20.tar.gz --> data related to the MiDAS S119 1.20 database (http://www.midasfieldguide.org/) ???
- MiDAS_S123_2.1.3.tar.gz --> data related to the MiDAS S123 2.1.3 database (http://www.midasfieldguide.org/) ???

**Comment by mariabernard** [comment]
I see your proposal only now.

It's done ! 
http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/

following your example

Thanks
