### ISSUE TITLE
FROGS 3.0.0 install - PEAR install

### ISSUE THREAD

**Issue by Toliman06** [geraldinepascal/FROGS#36]
Hi,

I'm tryong to install pear 0.9.10 as required by following the givien link in FROGS github documentation (https://sco.h-its.org/exelixis/web/software/pear/) but when I do it, the latest version is 0.9.8...

Where could I find the right version of the program?

Denis

**Comment by Toliman06** [comment]
There is a new download page here: https://www.h-its.org/en/research/sco/software/#NextGenerationSequencingSequenceAnalysis

but you can only download the 0.9.11 version... (I will try this one...)

**Comment by mariabernard** [comment]
hi,

Pear is not required, as it is under a licence for non accademic people. 
We fixed dependancies versions, because we can't test every new dependancy version. But yes in very most cases it should work.
