### ISSUE TITLE
FROGS 3.0.0 install - ITSx 1.0.11 install

### ISSUE THREAD

**Issue by Toliman06** [geraldinepascal/FROGS#37]
Hi (again...),

I'm currently installing ITSx 1.0.11 and I have some problem:
- I'm installing HMMER 3.2
- I'm installing ITSx 1.0.11
- And I removing the *.h3* files and recreate them using my hmmer version.

At this step, I have an error message: 

> Step 30/30 : RUN cd $LIBEXEC ; rm ITSx_db/HMMs/*.h3* &&	for hmm in ls  ITSx_db/HMMs/*.hmm ; do hmmpress $hmm;  done
>  ---> Running in f8bbbfe977d2
> Working...    done.
> Pressed and indexed 88 HMMs (88 names).
> Models pressed into binary file:   ITSx_db/HMMs/A.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/A.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/A.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/A.hmm.h3p
> Working...    done.
> Pressed and indexed 15 HMMs (15 names).
> Models pressed into binary file:   ITSx_db/HMMs/B.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/B.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/B.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/B.hmm.h3p
> Working...    done.
> Pressed and indexed 20 HMMs (20 names).
> Models pressed into binary file:   ITSx_db/HMMs/C.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/C.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/C.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/C.hmm.h3p
> Working...    done.
> Pressed and indexed 25 HMMs (25 names).
> Models pressed into binary file:   ITSx_db/HMMs/D.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/D.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/D.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/D.hmm.h3p
> Working...    done.
> Pressed and indexed 14 HMMs (14 names).
> Models pressed into binary file:   ITSx_db/HMMs/E.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/E.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/E.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/E.hmm.h3p
> Working...    done.
> Pressed and indexed 421 HMMs (421 names).
> Models pressed into binary file:   ITSx_db/HMMs/F.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/F.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/F.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/F.hmm.h3p
> Working...    done.
> Pressed and indexed 54 HMMs (54 names).
> Models pressed into binary file:   ITSx_db/HMMs/G.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/G.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/G.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/G.hmm.h3p
> Working...    done.
> Pressed and indexed 24 HMMs (24 names).
> Models pressed into binary file:   ITSx_db/HMMs/H.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/H.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/H.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/H.hmm.h3p
> Working...    done.
> Pressed and indexed 5 HMMs (5 names).
> Models pressed into binary file:   ITSx_db/HMMs/I.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/I.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/I.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/I.hmm.h3p
> Working...    done.
> Pressed and indexed 39 HMMs (39 names).
> Models pressed into binary file:   ITSx_db/HMMs/L.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/L.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/L.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/L.hmm.h3p
> Working...    done.
> Pressed and indexed 354 HMMs (354 names).
> Models pressed into binary file:   ITSx_db/HMMs/M.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/M.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/M.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/M.hmm.h3p
> 
> **Error: File format problem in trying to open HMM file ITSx_db/HMMs/N.hmm.
> �**
> 
> Working...    done.
> Pressed and indexed 71 HMMs (71 names).
> Models pressed into binary file:   ITSx_db/HMMs/O.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/O.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/O.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/O.hmm.h3p
> Working...    done.
> Pressed and indexed 10 HMMs (10 names).
> Models pressed into binary file:   ITSx_db/HMMs/P.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/P.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/P.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/P.hmm.h3p
> Working...    done.
> Pressed and indexed 7 HMMs (7 names).
> Models pressed into binary file:   ITSx_db/HMMs/Q.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/Q.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/Q.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/Q.hmm.h3p
> **Working...    /bin/bash: line 1:    27 Segmentation fault      (core dumped) hmmpress $hmm**
> Working...    done.
> Pressed and indexed 8 HMMs (8 names).
> Models pressed into binary file:   ITSx_db/HMMs/S.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/S.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/S.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/S.hmm.h3p
> Working...    done.
> Pressed and indexed 224 HMMs (224 names).
> Models pressed into binary file:   ITSx_db/HMMs/T.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/T.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/T.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/T.hmm.h3p
> Working...    done.
> Pressed and indexed 4 HMMs (4 names).
> Models pressed into binary file:   ITSx_db/HMMs/U.hmm.h3m
> SSI index for binary model file:   ITSx_db/HMMs/U.hmm.h3i
> Profiles (MSV part) pressed into:  ITSx_db/HMMs/U.hmm.h3f
> Profiles (remainder) pressed into: ITSx_db/HMMs/U.hmm.h3p

I think this is due to a lack files for the "N":  the N.hmm file size is 0 bytes and there is no other *.h3* files in the ITSx tar.gz original downloaded file...

Is it a normal behaviour?

**Comment by mariabernard** [comment]
Hi,

I did not have any trouble installing ITSx, but yes if you miss some .hmm files it will not work. Please contact ISX support or try to download the file again.

In fact for FROGS (for now) it is not really a problem as we only use F.hmm* files (for fungi), and you seem to not have  any problems with it.
