### ISSUE TITLE
Typo error in INSTALL_from_source.md

### ISSUE THREAD

**Issue by Toliman06** [geraldinepascal/FROGS#40]
In section 5) swarm 2.2.2, for FROGS Clustering, there is a "-" missing in the "./bin/swarm -version" command line (--version) ;)

**Comment by mariabernard** [comment]
thanks,

new pre realese 3.1 take your comment into account

**Comment by Toliman06** [comment]
I am also not sure, but there is some problems with the INSTALL_from_source.md:
we define out bin directory at the begining (BIN_DIR=$DIR/bin) but after, in the script, we are using commandes with "/home/frogs/bin/". Might not be $BIN_DIR?

/home/frogs/bin/ is used in:
10) Needlall 6.6.0.0, for FROGS Affiliation_OTU
11) MAFFT 7.407, for FROGS Tree

**Comment by mariabernard** [comment]
Your are right for section 10) Needleall.

For section 11) MAFFT this is an example, since you need to write the value of your BIN_DIR variable, you can't use "$BIN_DIR" in the Makefile.

If you wait few days conda receipt will be availbale, and FROGS will also be available in the Toolshed. This will be the adviced way to intall FROGS.

**Comment by Toliman06** [comment]
I will use the conda version, but I wanted to install FROGS by myself (as you know I tried for a long time...)

Just one last thing: in the Test FROGS sections, the code
`sh test.sh ~/FROGS <NB_CPU> <JAVA_MEM> <OUT_FOLDER>`
must be
`sh test.sh ~/FROGS-3.1.0/ <NB_CPU> <JAVA_MEM> <OUT_FOLDER>`

**Comment by Toliman06** [comment]
and it's finally work... failed:
```
~/FROGS-3.1.0/test$ sh test.sh ~/FROGS-3.1.0/ 4 4 ./test_results/
Step preprocess : Flash lundi 7 janvier 2019, 14:39:23 (UTC+0100)
Step preprocess : Vsearch lundi 7 janvier 2019, 14:39:54 (UTC+0100)
Step clustering lundi 7 janvier 2019, 14:40:29 (UTC+0100)
Step remove_chimera lundi 7 janvier 2019, 14:43:08 (UTC+0100)
Step filters lundi 7 janvier 2019, 14:44:16 (UTC+0100)
Step ITSx lundi 7 janvier 2019, 14:44:23 (UTC+0100)
Step affiliation_OTU lundi 7 janvier 2019, 14:44:26 (UTC+0100)
Step affiliation_postprocess lundi 7 janvier 2019, 14:44:45 (UTC+0100)
Step clusters_stat lundi 7 janvier 2019, 14:44:45 (UTC+0100)
Step affiliations_stat lundi 7 janvier 2019, 14:44:45 (UTC+0100)
Step biom_to_tsv lundi 7 janvier 2019, 14:44:47 (UTC+0100)
Step biom_to_stdBiom lundi 7 janvier 2019, 14:44:47 (UTC+0100)
Step tsv_to_biom lundi 7 janvier 2019, 14:44:47 (UTC+0100)
Step tree : mafft lundi 7 janvier 2019, 14:44:47 (UTC+0100)
test.sh: 257: test.sh: tree.py: Permission denied
Error in tree : mafft
```
then 
```
/FROGS-3.1.0/tools/tree$ ll
total 52
drwxrwxr-x  2 dunoyerd dunoyerd  4096 janv.  4 15:03 ./
drwxrwxr-x 25 dunoyerd dunoyerd  4096 janv.  4 15:03 ../
-rwxrwxr-x  1 dunoyerd dunoyerd   454 janv.  4 15:03 test.sh*
-rw-rw-r--  1 dunoyerd dunoyerd 13958 janv.  4 15:03 tree.py
-rw-rw-r--  1 dunoyerd dunoyerd 22482 janv.  4 15:03 tree_tpl.html
```
chmod +x solved the problem...
anyone else had this problem?
(then, it's working fine know, even if I had to copy RDPtools .jar from a previous installation...)

**Comment by mariabernard** [comment]
for the FROGS test command line, the correction applied is:
`sh test.sh ../ <NB_CPU> <JAVA_MEM> <OUT_FOLDER>` as we recommand to move to $FROGS_test in the first step.

for the tree.py rigths, I never noticed that! that's strange, so thanks for your test.
