### ISSUE TITLE
Question: itsx.py --input-count

### ISSUE THREAD

**Issue by Toliman06** [geraldinepascal/FROGS#41]
Hi,

In the itsx.py file, there is a "--input-count" input argument.

When I check the code, the argument is never used... What this argument is used for?

**Comment by mariabernard** [comment]
Hi,

you are right.

Initially we wanted to use itsx.py after any other step (preprocessing, clustering, ....), so we need to take into account abundances in .count format and in .biom format.

But ITSx is time consuming, so we ~~strongly recommend~~ impose to use it after filters.py (at least after clustering.py). It seems that we forgot to remove the --input-count option, but in fact it is not used.

Thanks for the comment
