### ISSUE TITLE
RDPTools installation problem

### ISSUE THREAD

**Issue by JeremyTournayre** [geraldinepascal/FROGS#45]
Hello,

In order to use FROGS I need to install RDPTools on my computer,
I had to resolve several errors when I launch the make command of RDPTools:
I had to use a java jdk version at 8 instead of 11
I had to modify the url http://repo2.maven by https://repo1.maven.

Unfortunately I am stuck with this error :
RDPTools/Clustering/build.xml:122: Warning: Could not find resource file "/RDPTools/Clustering/lib/jaxb-api-2.2.7.jar" to copy.

Indeed, I have only in my "lib" dir these files :
"RDPTools/Clustering/lib/commons-cli-1.2.jar
RDPTools/Clustering/lib/commons-codec-1.8.jar
RDPTools/Clustering/lib/commons-io-2.4.jar
RDPTools/Clustering/lib/jaxb-impl-2.2.7.jar
RDPTools/Clustering/lib/junit-4.8.2.jar"

Can you help me please? 
I forwarded this error to the github of RDPTools :  https://github.com/rdpstaff/RDPTools/issues/29

Sincerely,

Jérémy Tournayre

**Comment by mariabernard** [comment]
Hello,

Did you follow the [INTSALL_from_source.md](https://github.com/geraldinepascal/FROGS/blob/master/INSTALL_from_source.md) recommendations ? 

I can not test all installation procedures, but this one works for me and others.
The error does'nt mean anything to me, so I am affraid, I will not be able to help you.

The other and much simpler way to install FROGS is to use conda.
You simply need to install [miniconda ](https://docs.conda.io/en/latest/miniconda.html)and then 
```
conda create --name FROGS_3.1 frogs=3.1.0
# to use FROGS, first you need to activate your environment
source activate FROGS_3.1
```
This will install everything you need despite what you already have on your computer.

Maria

**Comment by mariabernard** [comment]
Hi

I do not know if my previous answer solved your problem.
You must know that RDPTools version 2.0.2 is not more installabe, if you still have some troubles you must update RDPTools with version 2.0.3, for detail see https://github.com/rdpstaff/RDPTools/issues/31

I publish the conda receip for this version : https://anaconda.org/bioconda/rdptools
