### ISSUE TITLE
Update of Unite (databanks/assignation)

### ISSUE THREAD

**Issue by anlebreton** [geraldinepascal/FROGS#46]
Hello,
I'm currently using  FROGS Affiliation OTU in Galaxy with Unite. I noticed that an update of Unite was available (v.8.2 - https://unite.ut.ee/repository.php), is it possible to format it for FROGS ? 

Best regards,
Annie

**Comment by mariabernard** [comment]
Hi,

The Unite version 8.2 is available here : http://genoweb.toulouse.inra.fr/frogs_databanks/assignation/Unite/
One is specific of Fungi the other contain all Eukaryota.

Best regards

Maria

**Comment by anlebreton** [comment]
Thanks !
