### ISSUE TITLE
phyloseq_composition.py script fails

### ISSUE THREAD

**Issue by ahorvath** [geraldinepascal/FROGS#53]
Dear Authors,

We are testing the new version of Frogs (3.2.2) and bumped into the following error:
Can you please help us solve this issue?

[FROGS_error.zip](https://github.com/geraldinepascal/FROGS/files/6426818/FROGS_error.zip)

Many thanks in advance.
Best,
Attila

**Comment by mariabernard** [comment]
Dear Attila,

I download your files and launch the exact same command and everything is fine.
I tested with the varExp set to SampleID and set to Condition.

Could you please indicate me how you install FROGS?
Could you test again your command by adding the --debug option and send me the temporary stderr file of the Rscript command.

**Comment by ahorvath** [comment]
We could find the issue using the debug option. Works now, thanks for your help, @mariabernard!
